import { Link, router, usePage } from '@inertiajs/react';
import AppLayout from '../../../Layouts/AppLayout';

type Product = { id: number; title: string; price: string; stock: number; status: string; condition: string; images?: string[] };
type Props = { products: { data: Product[]; links: { url: string | null; label: string; active: boolean }[] }; shop: { name: string } | null; flash?: { success?: string } };

export default function Index() {
    const { products, shop, flash } = usePage<Props>().props;
    return <AppLayout><section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Seller tools</p><h1 className="mt-2 text-4xl font-black">{shop?.name || 'My products'}</h1><p className="mt-2 text-slate-600">Manage your catalog, pricing, stock, and visibility.</p></div><Link href="/seller/products/create" className="rounded-xl bg-teal-700 px-5 py-3 font-bold text-white">Add product</Link></div>{flash?.success && <div className="mt-6 rounded-xl bg-emerald-50 p-4 text-emerald-700">{flash.success}</div>}<div className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200"><div className="hidden grid-cols-[1fr_8rem_7rem_8rem_8rem] gap-4 border-b border-slate-100 px-6 py-4 text-xs font-bold uppercase tracking-widest text-slate-400 sm:grid"><span>Product</span><span>Price</span><span>Stock</span><span>Status</span><span>Actions</span></div>{products.data.map((product) => <div key={product.id} className="grid gap-3 border-b border-slate-100 px-6 py-5 sm:grid-cols-[1fr_8rem_7rem_8rem_8rem] sm:items-center sm:gap-4"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-xl bg-teal-50">{product.images?.[0] ? <img src={product.images[0]} alt="" className="h-full w-full object-cover" /> : '✦'}</div><div><p className="font-black">{product.title}</p><p className="text-xs capitalize text-slate-500">{product.condition}</p></div></div><p className="font-bold text-teal-700">{Number(product.price).toLocaleString()} MMK</p><p className="text-sm text-slate-600">{product.stock} units</p><p><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize">{product.status}</span></p><div className="flex gap-3 text-sm font-bold"><Link href={`/seller/products/${product.id}/edit`} className="text-teal-700">Edit</Link><button onClick={() => { if (confirm('Hide this product?')) router.delete(`/seller/products/${product.id}`); }} className="text-red-600">Hide</button></div></div>)}{products.data.length === 0 && <div className="p-12 text-center text-slate-500">No products yet. Add your first product.</div>}</div><div className="mt-6 flex gap-2">{products.links.map((link) => link.url && <Link key={link.label} href={link.url} className={`rounded-lg px-3 py-2 text-sm ${link.active ? 'bg-teal-700 text-white' : 'bg-white ring-1 ring-slate-200'}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div></section></AppLayout>;
}
