import { Link, useForm, usePage } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';

type Offer = { id: number; product_id: number; title: string; price: string | number; amount: string | number; status: string; note?: string | null; other_name?: string; other_email?: string; created_at?: string };
type Product = { id: number; title: string; price: string | number };
type Props = { mode: 'buyer' | 'seller'; offers: Offer[]; products: Product[]; flash?: { success?: string } };

function OfferForm({ products }: { products: Product[] }) { const form = useForm({ product_id: products[0]?.id || 0, amount: '', note: '' }); return <form onSubmit={(event) => { event.preventDefault(); form.post('/offers'); }} className="grid gap-3 rounded-2xl bg-primary-50 p-5 sm:grid-cols-3"><h2 className="sm:col-span-3 font-bold text-primary-900">Make an offer</h2><select value={form.data.product_id} onChange={(event) => form.setData('product_id', Number(event.target.value))} className="rounded-xl border-white bg-white sm:col-span-3">{products.map((product) => <option key={product.id} value={product.id}>{product.title} · {Number(product.price).toLocaleString()} MMK</option>)}</select><input required type="number" min="1" placeholder="Your offer amount" value={form.data.amount} onChange={(event) => form.setData('amount', event.target.value)} className="rounded-xl border-white bg-white" /><input placeholder="Note (optional)" value={form.data.note} onChange={(event) => form.setData('note', event.target.value)} className="rounded-xl border-white bg-white sm:col-span-2" /><button disabled={form.processing} className="rounded-xl bg-primary-600 px-4 py-2 font-bold text-white sm:col-span-3">{form.processing ? 'Submitting...' : 'Submit offer'}</button></form>; }
function Review({ offer }: { offer: Offer }) { const form = useForm({ status: 'accepted', note: '' }); return <form onSubmit={(event) => { event.preventDefault(); form.post(`/seller/offers/${offer.id}/review`); }} className="mt-4 flex flex-wrap gap-2 border-t border-gray-100 pt-3"><select value={form.data.status} onChange={(event) => form.setData('status', event.target.value)} className="rounded-lg border-gray-200 text-sm"><option value="accepted">Accept</option><option value="rejected">Reject</option><option value="countered">Counter</option></select><input placeholder="Reply note" value={form.data.note} onChange={(event) => form.setData('note', event.target.value)} className="min-w-0 flex-1 rounded-lg border-gray-200 text-sm" /><button disabled={form.processing} className="rounded-lg bg-gray-900 px-3 py-2 text-sm font-bold text-white">Update</button></form>; }

export default function Index() { const { mode, offers, products, flash } = usePage<Props>().props; return <AppLayout><section className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary-700">Easy Zay Mm</p><h1 className="mt-2 text-3xl font-black">{mode === 'seller' ? 'Customer offers' : 'My offers'}</h1><p className="mt-2 text-gray-500">{mode === 'seller' ? 'Review offers from interested buyers.' : 'Track your submitted product offers.'}</p></div><Link href="/products" className="rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-bold text-white">Browse products</Link></div>{flash?.success && <p className="mt-5 rounded-xl bg-emerald-50 p-4 text-emerald-700">{flash.success}</p>}{mode === 'buyer' && products.length > 0 && <div className="mt-8"><OfferForm products={products} /></div>}<div className="mt-8 space-y-4">{offers.length === 0 ? <div className="rounded-2xl bg-white p-12 text-center text-gray-500 shadow-sm ring-1 ring-gray-100">No offers yet.</div> : offers.map((offer) => <article key={offer.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/products/${offer.product_id}`} className="font-bold text-gray-900 hover:text-primary-700">{offer.title}</Link><p className="mt-1 text-sm text-gray-500">{mode === 'seller' ? `From ${offer.other_name || offer.other_email || 'Buyer'}` : `Seller: ${offer.other_name || 'Seller'}`} · Listed {Number(offer.price).toLocaleString()} MMK</p></div><span className="rounded-full bg-primary-50 px-3 py-1 text-xs font-bold capitalize text-primary-700">{offer.status}</span></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xl font-black text-primary-700">{Number(offer.amount).toLocaleString()} MMK</p><p className="text-sm text-gray-500">{offer.note || 'No note provided.'}</p></div>{mode === 'seller' && offer.status === 'pending' && <Review offer={offer} />}</article>)}</div></section></AppLayout>; }
