<?php

use App\Http\Controllers\Web\AdminController;
use App\Http\Controllers\Web\AuthController;
use App\Http\Controllers\Web\BusinessController;
use App\Http\Controllers\Web\CartController;
use App\Http\Controllers\Web\ChatController;
use App\Http\Controllers\Web\ContentController;
use App\Http\Controllers\Web\MarketplaceController;
use App\Http\Controllers\Web\OfferController;
use App\Http\Controllers\Web\OperationsController;
use App\Http\Controllers\Web\ProductController;
use App\Http\Controllers\Web\ReviewController;
use App\Http\Controllers\Web\RoleController;
use App\Http\Controllers\Web\ShopController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/', [MarketplaceController::class, 'home'])->name('home');
Route::get('/products', [MarketplaceController::class, 'products'])->name('products.index');
Route::get('/products/{product}', [MarketplaceController::class, 'product'])->name('products.show');
Route::get('/categories', [OperationsController::class, 'user'])->defaults('screen', 'categories')->name('categories.index');
Route::get('/shops', [OperationsController::class, 'user'])->defaults('screen', 'shops')->name('shops.index');
Route::get('/shops/{shop}', [ShopController::class, 'show'])->name('shops.show');
Route::get('/cart', [CartController::class, 'index'])->name('cart.index');
Route::post('/cart/{product}', [CartController::class, 'add'])->name('cart.add');
Route::put('/cart', [CartController::class, 'update'])->name('cart.update');
Route::delete('/cart/{product}', [CartController::class, 'remove'])->name('cart.remove');
Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:6,1');
    Route::post('/forgot-password', [AuthController::class, 'sendPasswordReset'])->middleware('throttle:5,1')->name('password.email');
    Route::get('/register', [AuthController::class, 'showRegister'])->name('register');
    Route::post('/register', [AuthController::class, 'register']);
});
Route::middleware(['auth', 'active.user'])->group(function (): void {
    Route::get('/dashboard', [MarketplaceController::class, 'dashboard'])->name('dashboard');
    Route::get('/profile/complete', [AuthController::class, 'showProfileCompletion'])->name('profile.complete');
    Route::post('/profile/phone/request', [AuthController::class, 'requestPhoneOtp'])->name('profile.phone.request')->middleware('throttle:5,1');
    Route::post('/profile/phone/verify', [AuthController::class, 'verifyPhoneOtp'])->name('profile.phone.verify')->middleware('throttle:10,1');
    Route::post('/profile/complete', [AuthController::class, 'completeProfile'])->name('profile.complete.store');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/checkout', [CartController::class, 'checkout'])->name('checkout')->middleware('throttle:30,1');
    Route::post('/checkout', [CartController::class, 'placeOrder'])->name('checkout.place')->middleware('throttle:10,1');
    Route::get('/orders', [CartController::class, 'orders'])->name('orders.index');
    Route::get('/orders/{order}', [CartController::class, 'order'])->name('orders.show');
    Route::get('/favorites', [OperationsController::class, 'user'])->defaults('screen', 'favorites')->name('favorites.index');
    Route::get('/notifications', [OperationsController::class, 'user'])->defaults('screen', 'notifications')->name('notifications.index');
    Route::get('/chats', [OperationsController::class, 'user'])->defaults('screen', 'chats')->name('chats.index');
    Route::post('/chats/start', [ChatController::class, 'start'])->name('chats.start')->middleware('throttle:20,1');
    Route::get('/chats/{conversation}', [ChatController::class, 'show'])->name('chats.show');
    Route::post('/chats/{conversation}/messages', [ChatController::class, 'store'])->name('chats.messages.store')->middleware('throttle:30,1');
    Route::get('/offers', [OfferController::class, 'index'])->name('offers.index');
    Route::post('/offers', [OfferController::class, 'store'])->name('offers.store');
    Route::get('/reviews', [ReviewController::class, 'index'])->name('reviews.index');
    Route::post('/products/{product}/reviews', [ReviewController::class, 'store'])->name('reviews.store');
    Route::get('/profile', [AuthController::class, 'showProfile'])->name('profile.index');
    Route::get('/addresses', [OperationsController::class, 'user'])->defaults('screen', 'addresses')->name('addresses.index');
    Route::get('/help', [OperationsController::class, 'user'])->defaults('screen', 'help')->name('help.index');
    Route::post('/favorites/{product}/toggle', [OperationsController::class, 'toggleFavorite'])->name('favorites.toggle');
    Route::post('/addresses', [OperationsController::class, 'storeAddress'])->name('addresses.store');
    Route::delete('/addresses/{address}', [OperationsController::class, 'deleteAddress'])->name('addresses.destroy');
    Route::post('/notifications/read-all', [OperationsController::class, 'markNotificationsRead'])->name('notifications.read-all');
    Route::post('/shops/{shop}/follow', [ShopController::class, 'toggleFollow'])->name('shops.follow');
    Route::post('/shops/{shop}/chat', [ShopController::class, 'startChat'])->name('shops.chat');
    Route::middleware('role:user,admin')->group(function (): void {
        Route::get('/seller/shop/create', [RoleController::class, 'createShop'])->name('seller.shop.create');
        Route::post('/seller/shop', [RoleController::class, 'storeShop'])->name('seller.shop.store');
    });
    Route::middleware('seller')->group(function (): void {
        Route::get('/seller/verification', [RoleController::class, 'verification'])->name('seller.verification');
        Route::post('/seller/verification', [RoleController::class, 'submitVerification'])->name('seller.verification.submit');
    });
    Route::middleware('verified.seller')->prefix('seller/products')->group(function (): void {
        Route::get('/', [ProductController::class, 'index'])->name('seller.products.index');
        Route::get('/create', [ProductController::class, 'create'])->name('seller.products.create');
        Route::post('/', [ProductController::class, 'store'])->name('seller.products.store');
        Route::get('/{product}/edit', [ProductController::class, 'edit'])->name('seller.products.edit');
        Route::put('/{product}', [ProductController::class, 'update'])->name('seller.products.update');
        Route::delete('/{product}', [ProductController::class, 'destroy'])->name('seller.products.destroy');
    });
    Route::middleware('verified.seller')->prefix('seller')->group(function (): void {
        Route::get('/inventory', [BusinessController::class, 'inventory'])->name('seller.inventory');
        Route::post('/inventory/{product}/adjust', [BusinessController::class, 'adjust'])->name('seller.inventory.adjust');
        Route::get('/pos', [BusinessController::class, 'pos'])->name('seller.pos');
        Route::post('/pos', [BusinessController::class, 'sale'])->name('seller.pos.sale');
        Route::get('/expenses', [BusinessController::class, 'expenses'])->name('seller.expenses');
        Route::post('/expenses', [BusinessController::class, 'expense'])->name('seller.expenses.store');
        Route::get('/reports', [BusinessController::class, 'reports'])->name('seller.reports');
        Route::get('/orders', [OperationsController::class, 'seller'])->defaults('screen', 'orders')->name('seller.orders');
        Route::post('/orders/{order}/status/{status}', [OperationsController::class, 'updateOrderStatus'])->name('seller.orders.status');
        Route::get('/offers', [OfferController::class, 'index'])->name('seller.offers');
        Route::post('/offers/{offer}/review', [OfferController::class, 'review'])->name('seller.offers.review');
        Route::get('/customers', [OperationsController::class, 'seller'])->defaults('screen', 'customers')->name('seller.customers');
        Route::get('/analytics', [OperationsController::class, 'seller'])->defaults('screen', 'analytics')->name('seller.analytics');
        Route::get('/settings', [ContentController::class, 'sellerSettings'])->name('seller.settings');
        Route::put('/settings', [ContentController::class, 'updateSellerSettings'])->name('seller.settings.update');
        Route::get('/categories', [OperationsController::class, 'seller'])->defaults('screen', 'categories')->name('seller.categories');
    });
    Route::middleware('seller')->prefix('seller')->group(function (): void {
        Route::get('/', [BusinessController::class, 'dashboard'])->name('seller.dashboard');
    });
    Route::middleware('admin')->prefix('admin')->group(function (): void {
        Route::get('/', [AdminController::class, 'dashboard'])->name('admin.dashboard');
        Route::get('/verifications', [RoleController::class, 'adminVerifications'])->name('admin.verifications');
        Route::post('/verifications/{verification}/review', [RoleController::class, 'reviewVerification'])->name('admin.verifications.review');
        Route::get('/users', [OperationsController::class, 'admin'])->defaults('screen', 'users')->name('admin.users');
        Route::post('/users/{user}/status/{status}', [OperationsController::class, 'updateUserStatus'])->name('admin.users.status');
        Route::get('/shops', [OperationsController::class, 'admin'])->defaults('screen', 'shops')->name('admin.shops');
        Route::post('/shops/{shop}/status/{status}', [OperationsController::class, 'updateShopStatus'])->name('admin.shops.status');
        Route::get('/products', [OperationsController::class, 'admin'])->defaults('screen', 'products')->name('admin.products');
        Route::post('/products/{product}/status/{status}', [OperationsController::class, 'updateProductStatus'])->name('admin.products.status');
        Route::post('/products/{product}/delete', [OperationsController::class, 'deleteProduct'])->name('admin.products.delete');
        Route::get('/orders', [OperationsController::class, 'admin'])->defaults('screen', 'orders')->name('admin.orders');
        Route::post('/orders/{order}/status/{status}', [OperationsController::class, 'updateOrderStatus'])->name('admin.orders.status');
        Route::get('/reports', [OperationsController::class, 'admin'])->defaults('screen', 'reports')->name('admin.reports');
        Route::get('/categories', [OperationsController::class, 'admin'])->defaults('screen', 'categories')->name('admin.categories');
        Route::post('/categories', [OperationsController::class, 'storeCategory'])->name('admin.categories.store');
        Route::post('/categories/{category}/toggle', [OperationsController::class, 'toggleCategory'])->name('admin.categories.toggle');
        Route::get('/banners', [ContentController::class, 'banners'])->name('admin.banners');
        Route::post('/banners', [ContentController::class, 'storeBanner'])->name('admin.banners.store');
        Route::post('/banners/{banner}/toggle', [ContentController::class, 'toggleBanner'])->name('admin.banners.toggle');
        Route::get('/settings', [ContentController::class, 'settings'])->name('admin.settings');
        Route::put('/settings/{setting}', [ContentController::class, 'updateSetting'])->name('admin.settings.update');
    });
});
