export const useNotifications = (_userId: string | undefined) => {
  const sendNotification = async () => {
    throw new Error('Notifications are generated by trusted backend events only.');
  };

  return { sendNotification };
};
