import { Link, router, usePage } from '@inertiajs/react';
import { ArrowLeft, Search, ShoppingBag } from 'lucide-react';
import type { FormEvent } from 'react';
import AppLayout from '../../Layouts/AppLayout';

type Category = { id: number; name: string; slug: string; icon_url?: string | null };
type Product = { id: number; title: string; price: string | number; stock: number; images?: string[]; condition?: string; shop?: { name: string; verified?: boolean } };
type Props = { categories: Category[]; selected?: Category; products: Product[]; query?: string };

export default function Categories() {
    const { categories, selected, products, query = '' } = usePage<Props>().props;
    const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); router.get(selected ? `/categories/${selected.slug}` : '/categories', { q: data.get('q') || '' }, { preserveState: true, replace: true }); };
    return <AppLayout><div className="min-h-[calc(100vh-4rem)] bg-gray-50"><header className="sticky top-14 z-20 border-b border-gray-200 bg-white"><div className="flex items-center gap-2 px-4 py-3"><Link href="/" className="rounded-full p-2 hover:bg-gray-100"><ArrowLeft size={21} /></Link><h1 className="text-lg font-semibold">Categories</h1></div><form onSubmit={submit} className="px-4 pb-3"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} /><input name="q" defaultValue={query} placeholder="Search in category..." className="w-full rounded-full border-0 bg-gray-100 py-2 pl-9 pr-4 text-sm focus:bg-white focus:ring-2 focus:ring-primary-500" /></div></form></header><div className="flex"><aside className="sticky top-[8.5rem] h-[calc(100vh-8.5rem)] w-24 shrink-0 overflow-y-auto bg-gray-50 py-2 sm:w-32">{categories.map((category) => <Link key={category.id} href={`/categories/${category.slug}`} className={`block border-l-2 p-3 text-center transition-colors ${selected?.id === category.id ? 'border-primary-600 bg-white text-primary-600' : 'border-transparent text-gray-600 hover:bg-gray-100'}`}><div className="mx-auto mb-1 flex h-10 w-10 items-center justify-center overflow-hidden rounded-full bg-primary-50 font-bold">{category.icon_url ? <img src={category.icon_url} alt={category.name} className="h-full w-full object-cover" /> : category.name.charAt(0)}</div><span className="line-clamp-2 text-xs">{category.name}</span></Link>)}</aside><main className="min-w-0 flex-1 p-4 sm:p-6">{selected && <div className="mb-4"><h2 className="text-lg font-semibold text-gray-900">{selected.name}</h2><p className="text-sm text-gray-500">{products.length} products</p></div>}{products.length === 0 ? <div className="rounded-xl bg-white py-16 text-center text-gray-500">No products in this category</div> : <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{products.map((product) => <Link href={`/products/${product.id}`} key={product.id} className="overflow-hidden rounded-xl bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex aspect-square items-center justify-center bg-gray-100 text-gray-400">{product.images?.[0] ? <img src={product.images[0]} alt={product.title} className="h-full w-full object-cover" /> : <ShoppingBag size={32} />}</div><div className="p-3"><h3 className="line-clamp-2 text-sm font-medium text-gray-900">{product.title}</h3><p className="mt-1 font-bold text-primary-600">{Number(product.price).toLocaleString()} Ks</p><p className="mt-1 text-xs capitalize text-gray-500">{product.condition || 'new'} · {product.stock} left</p></div></Link>)}</div>}</main></div></div></AppLayout>;
}
