import { Link, router, usePage } from '@inertiajs/react';
import { ArrowLeft, Heart, ShoppingBag, Trash2 } from 'lucide-react';
import AppLayout from '../../Layouts/AppLayout';

type Product = { id: number; title: string; price: string | number; images?: string[]; stock: number; shop?: { name: string; verified?: boolean } };
type Favorite = { favorite_id: number; product: Product };
type Props = { favorites: Favorite[] };

export default function Favorites() { const { favorites } = usePage<Props>().props; return <AppLayout><section className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><div className="flex items-center gap-2"><Link href="/" className="rounded-full p-2 hover:bg-gray-100"><ArrowLeft size={21} /></Link><div><p className="text-xs font-bold uppercase tracking-widest text-primary-600">Saved items</p><h1 className="text-2xl font-bold">Favorites</h1></div></div>{favorites.length === 0 ? <div className="py-20 text-center"><Heart className="mx-auto mb-4 text-gray-300" size={64} /><h2 className="text-xl font-semibold">No Favorites Yet</h2><p className="mt-2 text-gray-500">Save products you love to find them later.</p><Link href="/products" className="mt-6 inline-flex rounded-xl bg-primary-600 px-6 py-3 font-semibold text-white">Start Shopping</Link></div> : <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{favorites.map(({ favorite_id, product }) => <div key={favorite_id} className="relative overflow-hidden rounded-xl bg-white shadow-sm"><Link href={`/products/${product.id}`}><div className="flex aspect-square items-center justify-center bg-gray-100 text-gray-400">{product.images?.[0] ? <img src={product.images[0]} alt={product.title} className="h-full w-full object-cover" /> : <ShoppingBag size={32} />}</div><div className="p-3"><p className="line-clamp-2 text-sm font-medium">{product.title}</p><p className="mt-1 font-bold text-primary-600">{Number(product.price).toLocaleString()} Ks</p><p className="mt-1 text-xs text-gray-500">{product.shop?.name || 'Marketplace seller'}</p></div></Link><button type="button" onClick={() => router.post(`/favorites/${product.id}/toggle`)} className="absolute right-2 top-2 rounded-full bg-white p-2 text-red-500 shadow" aria-label="Remove favorite"><Trash2 size={16} /></button></div>)}</div>}</section></AppLayout>; }
