import { Link, router, usePage } from '@inertiajs/react';
import { BadgeCheck, Grid2X2, List, Search, SlidersHorizontal, X } from 'lucide-react';
import { type FormEvent, useState } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import ProductImage from '../../Components/ProductImage';
import type { SharedProps } from '../../types';

type Product = { id: number; title: string; brand?: string; price: string | number; stock: number; condition?: string; images?: string[]; shop?: { name: string; slug: string; verified?: boolean } };
type Category = { name: string; slug: string };
type Filters = { q?: string; brand?: string; category?: string; shop?: string; verified?: string | boolean; condition?: string; min_price?: string; max_price?: string; sort?: string };
type Props = SharedProps & Record<string, unknown> & { products: { data: Product[]; links: { url: string | null; label: string; active: boolean }[]; total?: number }; categories: Category[]; filters: Filters };

export default function Index() {
    const { products, categories, filters } = usePage<Props>().props;
    const [filterOpen, setFilterOpen] = useState(false);
    const [view, setView] = useState<'grid' | 'list'>('grid');
    const hasFilters = Boolean(filters.q || filters.brand || filters.category || filters.shop || filters.verified || filters.condition || filters.min_price || filters.max_price || filters.sort);
    const submit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        const values = Object.fromEntries(new FormData(event.currentTarget).entries());
        Object.keys(values).forEach((key) => { if (!values[key]) delete values[key]; });
        router.get('/products', values, { preserveState: true, replace: true });
    };
    const clear = () => router.get('/products', {}, { preserveState: true, replace: true });

    return <AppLayout>
        <section className="mx-auto max-w-7xl px-4 py-5 pb-24 sm:px-6 sm:py-8 lg:px-8">
            <div className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary-600">Marketplace</p><h1 className="mt-1 text-2xl font-bold text-gray-900 sm:text-3xl">Find something useful</h1><p className="mt-1 text-sm text-gray-500">Discover products from verified local shops</p></div><button type="button" onClick={() => setFilterOpen(!filterOpen)} className={`flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold sm:hidden ${filterOpen ? 'bg-primary-600 text-white' : 'bg-white text-gray-700 ring-1 ring-gray-200'}`}><SlidersHorizontal size={17} /> Filters</button></div>
            <form onSubmit={submit} className={`mt-5 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm ${filterOpen ? 'block' : 'hidden sm:block'}`}>
                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><div className="relative lg:col-span-2"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} /><input name="q" defaultValue={filters.q} placeholder="Search products, brands, or shops..." className="w-full rounded-lg border-gray-300 pl-10 text-sm focus:border-primary-500 focus:ring-primary-500" /></div><select name="category" defaultValue={filters.category ?? ''} className="rounded-lg border-gray-300 text-sm"><option value="">All categories</option>{categories.map((category) => <option value={category.slug} key={category.slug}>{category.name}</option>)}</select><select name="condition" defaultValue={filters.condition ?? ''} className="rounded-lg border-gray-300 text-sm"><option value="">Any condition</option><option value="new">New</option><option value="used">Used</option><option value="refurbished">Refurbished</option></select><select name="sort" defaultValue={filters.sort ?? ''} className="rounded-lg border-gray-300 text-sm"><option value="">Recommended</option><option value="newest">Newest</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select><button className="rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-700">Search</button></div>
                <div className="mt-3 flex flex-wrap items-center gap-3"><input name="shop" defaultValue={filters.shop} placeholder="Shop or city" className="w-40 rounded-lg border-gray-300 text-sm" /><input name="min_price" defaultValue={filters.min_price} type="number" min="0" placeholder="Min price" className="w-32 rounded-lg border-gray-300 text-sm" /><input name="max_price" defaultValue={filters.max_price} type="number" min="0" placeholder="Max price" className="w-32 rounded-lg border-gray-300 text-sm" /><label className="flex items-center gap-2 text-sm text-gray-600"><input name="verified" value="1" type="checkbox" defaultChecked={filters.verified === true || filters.verified === '1'} className="rounded border-gray-300 text-primary-600 focus:ring-primary-500" />Verified shops</label>{hasFilters && <button type="button" onClick={clear} className="ml-auto flex items-center gap-1 text-sm font-medium text-gray-500 hover:text-red-600"><X size={15} /> Clear all</button>}</div>
            </form>
            <div className="mt-5 flex items-center justify-between"><p className="text-sm text-gray-500"><span className="font-semibold text-gray-900">{products.total ?? products.data.length}</span> products found</p><div className="flex rounded-lg bg-gray-100 p-1"><button type="button" onClick={() => setView('grid')} className={`rounded p-1.5 ${view === 'grid' ? 'bg-white text-primary-600 shadow-sm' : 'text-gray-500'}`} aria-label="Grid view"><Grid2X2 size={17} /></button><button type="button" onClick={() => setView('list')} className={`rounded p-1.5 ${view === 'list' ? 'bg-white text-primary-600 shadow-sm' : 'text-gray-500'}`} aria-label="List view"><List size={17} /></button></div></div>
            {products.data.length === 0 ? <div className="mt-4 rounded-2xl border border-gray-200 bg-white p-14 text-center"><Search className="mx-auto text-gray-300" size={48} /><h2 className="mt-4 font-bold text-gray-900">No products found</h2><p className="mt-1 text-sm text-gray-500">Try changing your search or clearing the filters.</p>{hasFilters && <button type="button" onClick={clear} className="mt-4 rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white">Clear filters</button>}</div> : <div className={`mt-4 ${view === 'grid' ? 'grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4' : 'space-y-3'}`}>{products.data.map((product) => <Link href={`/products/${product.id}`} key={product.id} className={`group overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-primary-200 hover:shadow-md ${view === 'list' ? 'flex items-center gap-4 p-3' : ''}`}><div className={`${view === 'list' ? 'h-24 w-24 shrink-0 rounded-xl' : 'aspect-square w-full'} flex items-center justify-center overflow-hidden bg-gray-100 text-4xl text-primary-200`}>{product.images?.[0] ? <ProductImage src={product.images[0]} alt={product.title} className="transition group-hover:scale-105" /> : <span>✦</span>}</div><div className={`${view === 'list' ? 'min-w-0 flex-1' : 'p-3 sm:p-4'}`}><div className="flex items-center justify-between gap-2"><p className="truncate text-[11px] font-medium text-gray-500">{product.shop?.name || 'Marketplace seller'}</p>{product.shop?.verified && <BadgeCheck className="shrink-0 text-primary-600" size={16} />}</div><h2 className="mt-1 line-clamp-2 text-sm font-semibold text-gray-900 sm:text-base">{product.title}</h2><p className="mt-2 text-base font-bold text-primary-600 sm:text-lg">{Number(product.price).toLocaleString()} MMK</p><p className="mt-1 text-xs capitalize text-gray-500">{product.condition || 'new'} · {product.stock} in stock</p></div></Link>)}</div>}
            <div className="mt-6 flex flex-wrap justify-center gap-2">{products.links.map((link) => link.url && <Link key={link.label} href={link.url} className={`rounded-lg px-3 py-2 text-sm ${link.active ? 'bg-primary-600 text-white' : 'bg-white text-gray-600 ring-1 ring-gray-200'}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div>
        </section>
    </AppLayout>;
}
