import { Link, router, usePage } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';

type Product = { id: number; title: string; description?: string; price: string | number; stock: number; images?: string[]; shop?: { name: string; slug: string } };
type Props = { products: { data: Product[]; links: { url: string | null; label: string; active: boolean }[] }; filters: { q: string } };

export default function Index() {
    const { products, filters } = usePage<Props>().props;
    return <AppLayout><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Marketplace</p><h1 className="mt-2 text-4xl font-black">Find something useful</h1></div><form onSubmit={(e) => { e.preventDefault(); const value = new FormData(e.currentTarget).get('q')?.toString() || ''; router.get('/products', { q: value }, { preserveState: true }); }} className="flex gap-2"><input name="q" defaultValue={filters.q} placeholder="Search products" className="rounded-xl border-slate-300" /><button className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Search</button></form></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.data.map((product) => <Link href={`/products/${product.id}`} key={product.id} className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex aspect-square items-center justify-center bg-gradient-to-br from-teal-50 to-cyan-100 text-5xl">{product.images?.[0] ? <img src={product.images[0]} alt="" className="h-full w-full object-cover" /> : '✦'}</div><div className="p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{product.shop?.name || 'Marketplace seller'}</p><h2 className="mt-2 line-clamp-2 text-lg font-black">{product.title}</h2><p className="mt-3 text-xl font-black text-teal-700">{Number(product.price).toLocaleString()} MMK</p><p className="mt-1 text-sm text-slate-500">{product.stock} in stock</p></div></Link>)}{products.data.length === 0 && <div className="col-span-full rounded-3xl bg-white p-12 text-center text-slate-500">No products found.</div>}</div><div className="mt-8 flex flex-wrap gap-2">{products.links.map((link) => link.url && <Link key={link.label} href={link.url} className={`rounded-lg px-3 py-2 text-sm ${link.active ? 'bg-teal-700 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div></section></AppLayout>;
}
