import { Link, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, BadgeCheck, Heart, MapPin, MessageCircle, Share2, ShieldCheck, ShoppingCart, Star } from 'lucide-react';
import AppLayout from '../../Layouts/AppLayout';
import ProductImage from '../../Components/ProductImage';

type Product = { id: number; title: string; description?: string; price: string; stock: number; condition: string; images?: string[]; shop?: { name: string; verified: boolean; address?: string }; seller?: { name: string } };
type Review = { id: number; rating: number; body?: string | null; user_name: string; created_at?: string };
type Props = { product: Product; reviews: Review[]; reviewSummary: { count: number; average: number }; auth?: { user?: { id: number } }; isFavorite?: boolean };

function Stars({ rating }: { rating: number }) {
    return <span className="inline-flex items-center gap-0.5 text-amber-500" aria-label={`${rating} out of 5 stars`}>{Array.from({ length: 5 }, (_, index) => <Star key={index} size={16} fill={index < Math.round(rating) ? 'currentColor' : 'none'} />)}</span>;
}

export default function Show() {
    const { product, auth, isFavorite = false, reviews = [], reviewSummary = { count: 0, average: 0 } } = usePage<Props>().props;
    const form = useForm({ quantity: 1 });
    const chatForm = useForm({ product_id: product.id });
    const favoriteForm = useForm({});
    return <AppLayout><section className="mx-auto max-w-6xl px-4 py-6 pb-28 sm:px-6 sm:py-8 lg:px-8">
        <Link href="/products" className="inline-flex items-center gap-1 text-sm font-medium text-gray-500 hover:text-primary-600"><ArrowLeft size={16} /> Back to marketplace</Link>
        <div className="mt-5 grid gap-5 lg:grid-cols-2 lg:gap-10"><div><div className="relative flex aspect-square items-center justify-center overflow-hidden rounded-xl bg-gray-100 text-8xl text-primary-200">{product.images?.[0] ? <ProductImage src={product.images[0]} alt={product.title} /> : <span>✦</span>}<button type="button" aria-label={isFavorite ? 'Remove from favorites' : 'Add to favorites'} onClick={() => auth?.user ? favoriteForm.post(`/favorites/${product.id}/toggle`, { preserveScroll: true }) : window.location.assign('/login')} className={`absolute right-3 top-3 rounded-full bg-white/90 p-2.5 shadow-sm ${isFavorite ? 'text-rose-500' : 'text-gray-600'}`}><Heart size={19} fill={isFavorite ? 'currentColor' : 'none'} /></button></div>{product.images && product.images.length > 1 && <div className="mt-3 flex gap-2 overflow-x-auto">{product.images.map((image) => <div key={image} className="h-16 w-16 shrink-0 overflow-hidden rounded-lg border border-gray-200"><ProductImage src={image} alt="" /></div>)}</div>}</div>
            <div className="flex flex-col"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold uppercase tracking-wider text-primary-600">{product.condition || 'New'} condition</p><button type="button" className="rounded-lg p-2 text-gray-500 hover:bg-gray-100" aria-label="Share product"><Share2 size={18} /></button></div><h1 className="mt-2 text-2xl font-bold text-gray-900 sm:text-3xl">{product.title}</h1><p className="mt-4 text-2xl font-bold text-primary-600 sm:text-3xl">{Number(product.price).toLocaleString()} Ks</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-gray-100 px-3 py-1.5 capitalize text-gray-600">{product.condition || 'new'}</span><span className={`rounded-full px-3 py-1.5 ${product.stock > 0 ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{product.stock > 0 ? `${product.stock} in stock` : 'Out of stock'}</span></div>
                <Link href="#reviews" className="mt-4 inline-flex w-fit items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-sm font-bold text-amber-700 hover:bg-amber-100"><Stars rating={reviewSummary.average} /><span>{reviewSummary.count ? `${reviewSummary.average} · ${reviewSummary.count} review${reviewSummary.count === 1 ? '' : 's'}` : 'Be the first to review'}</span></Link>
                <div className="mt-6 border-t border-gray-100 pt-5"><h2 className="font-semibold text-gray-900">Description</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-gray-600">{product.description || 'No description provided.'}</p></div><div className="mt-6 rounded-xl border border-gray-200 bg-gray-50 p-4"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-100 font-bold text-primary-700">{(product.shop?.name || product.seller?.name || 'S').charAt(0)}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-gray-900">{product.shop?.name || product.seller?.name || 'Marketplace seller'}</p><p className="mt-1 flex items-center gap-1 text-xs text-gray-500"><Star size={13} className="fill-yellow-400 text-yellow-400" /> Trusted seller</p></div>{product.shop?.verified && <BadgeCheck size={20} className="text-primary-600" />}</div>{product.shop?.address && <p className="mt-3 flex items-center gap-1 text-xs text-gray-500"><MapPin size={14} />{product.shop.address}</p>}</div><form onSubmit={(event) => { event.preventDefault(); form.post(`/cart/${product.id}`); }} className="mt-6 flex gap-3"><input type="number" min="1" max={product.stock} value={form.data.quantity} onChange={(event) => form.setData('quantity', Number(event.target.value))} className="w-20 rounded-lg border-gray-300 text-center text-sm" /><button disabled={form.processing || product.stock < 1} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-primary-600 px-5 py-3 text-sm font-semibold text-white hover:bg-primary-700 disabled:bg-gray-300"><ShoppingCart size={18} />{product.stock ? 'Add to cart' : 'Out of stock'}</button></form><div className="mt-3 grid grid-cols-2 gap-2">{auth?.user && <button onClick={() => chatForm.post('/chats/start')} disabled={chatForm.processing} className="flex items-center justify-center gap-2 rounded-lg border border-primary-200 bg-primary-50 px-3 py-2.5 text-sm font-semibold text-primary-700"><MessageCircle size={16} />{chatForm.processing ? 'Opening...' : 'Chat seller'}</button>}<div className="flex items-center justify-center gap-2 rounded-lg bg-emerald-50 px-3 py-2.5 text-xs font-medium text-emerald-700"><ShieldCheck size={16} /> Buyer protection</div></div></div></div>
        <section id="reviews" className="mt-12 border-t border-gray-200 pt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary-700">Customer feedback</p><h2 className="mt-1 text-2xl font-black text-gray-950">Product reviews</h2></div><div className="flex items-center gap-3 rounded-2xl bg-white px-4 py-3 shadow-sm ring-1 ring-gray-100"><span className="text-3xl font-black text-amber-500">{reviewSummary.average || '—'}</span><div><Stars rating={reviewSummary.average} /><p className="mt-1 text-xs text-gray-500">{reviewSummary.count} review{reviewSummary.count === 1 ? '' : 's'}</p></div></div></div>{reviews.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed border-gray-300 bg-white p-10 text-center"><MessageCircle className="mx-auto text-gray-300" size={42} /><p className="mt-3 font-semibold text-gray-900">No reviews yet</p><p className="mt-1 text-sm text-gray-500">Verified buyers can share their experience from the Reviews page.</p>{auth?.user && <Link href="/reviews" className="mt-4 inline-flex rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-bold text-white">Go to Reviews</Link>}</div> : <div className="mt-5 grid gap-4 md:grid-cols-2">{reviews.map((review) => <article key={review.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-gray-900">{review.user_name}</p><p className="mt-1 text-xs text-gray-500">{review.created_at || 'Recently'}</p></div><Stars rating={review.rating} /></div>{review.body && <p className="mt-4 whitespace-pre-line text-sm leading-6 text-gray-700">{review.body}</p>}</article>)}</div>}</section>
    </section></AppLayout>;
}
