import { Link, usePage } from '@inertiajs/react';
import { AlertTriangle, Eye, FileCheck, Package, ShoppingBag, Store, Users } from 'lucide-react';
import AdminLayout from '../../Layouts/AdminLayout';

type Props = { stats: { users: number; shops: number; products: number; orders: number; pending_verifications: number }; recentOrders: { id: number; order_number: string; total: string | number; status: string; buyer?: { name: string }; shop?: { name: string }; created_at: string }[] };
export default function Dashboard() {
    const { stats, recentOrders } = usePage<Props>().props;
    const cards = [['Total Users', stats.users, Users, 'bg-blue-500'], ['Total Shops', stats.shops, Store, 'bg-green-500'], ['Total Products', stats.products, Package, 'bg-purple-500'], ['Total Orders', stats.orders, ShoppingBag, 'bg-orange-500']];
    return <AdminLayout title="Dashboard"><div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, Icon, color]) => <div key={label as string} className="rounded-xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-gray-500">{label as string}</p><p className="mt-1 text-3xl font-bold text-gray-900">{Number(value).toLocaleString()}</p><p className="mt-1 text-sm text-green-600">Live platform count</p></div><div className={`${color as string} rounded-lg p-3`}><Icon className="text-white" size={24} /></div></div></div>)}</div><div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-2"><div className="rounded-xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-lg font-semibold">Quick Actions</h3><div className="space-y-3"><Link href="/admin/verifications" className="flex items-center justify-between rounded-lg bg-yellow-50 p-4 hover:bg-yellow-100"><span className="flex items-center gap-3 font-medium text-yellow-800"><FileCheck size={20} />Pending Verifications</span><span className="rounded-full bg-yellow-200 px-3 py-1 text-sm font-medium text-yellow-800">{stats.pending_verifications}</span></Link><Link href="/admin/reports" className="flex items-center justify-between rounded-lg bg-red-50 p-4 hover:bg-red-100"><span className="flex items-center gap-3 font-medium text-red-800"><AlertTriangle size={20} />Pending Reports</span><span className="rounded-full bg-red-200 px-3 py-1 text-sm font-medium text-red-800">Review</span></Link><Link href="/admin/banners" className="flex items-center gap-3 rounded-lg bg-blue-50 p-4 font-medium text-blue-800 hover:bg-blue-100"><Eye size={20} />Manage Banners</Link></div></div><div className="rounded-xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-lg font-semibold">Recent Orders</h3>{recentOrders.length === 0 ? <p className="py-8 text-center text-gray-500">No recent orders</p> : <div className="space-y-3">{recentOrders.map((order) => <div key={order.id} className="flex items-center justify-between rounded-lg bg-gray-50 p-3"><div><p className="text-sm font-medium text-gray-900">#{order.order_number}</p><p className="text-xs text-gray-500">{order.buyer?.name || 'Buyer'} · {order.shop?.name || 'Marketplace'}</p></div><div className="text-right"><p className="font-semibold text-primary-600">{Number(order.total).toLocaleString()} Ks</p><span className="text-xs capitalize text-gray-500">{order.status}</span></div></div>)}</div>}</div></div></AdminLayout>;
}
