import { useForm, usePage } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';

type RequestItem = { id: number; status: string; evidence: string[]; note?: string | null; created_at: string; shop: { name: string; verification_status: string }; submitter: { name: string; email: string } };
type Props = { requests: { data: RequestItem[]; links: { url: string | null; label: string; active: boolean }[] }; flash?: { success?: string } };

function ReviewForm({ requestItem }: { requestItem: RequestItem }) {
    const form = useForm({ decision: 'approved', note: '' });
    return <form onSubmit={(e) => { e.preventDefault(); form.post(`/admin/verifications/${requestItem.id}/review`); }} className="mt-5 border-t border-slate-100 pt-5"><div className="grid gap-3 sm:grid-cols-[10rem_1fr_auto]"><select value={form.data.decision} onChange={(e) => form.setData('decision', e.target.value)} className="rounded-xl border-slate-300"><option value="approved">Approve</option><option value="rejected">Reject</option></select><input value={form.data.note} onChange={(e) => form.setData('note', e.target.value)} placeholder="Review note (required for a useful rejection)" className="rounded-xl border-slate-300" /><button disabled={form.processing} className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white disabled:opacity-50">Save review</button></div>{Object.values(form.errors).map((error) => <p key={error} className="mt-2 text-sm text-red-600">{error}</p>)}</form>;
}

export default function Verifications() {
    const { requests, flash } = usePage<Props>().props;
    return <AppLayout><section className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-primary-700">Admin moderation</p><h1 className="mt-2 text-4xl font-black">Shop verifications</h1>{flash?.success && <div className="mt-6 rounded-xl bg-emerald-50 p-4 text-emerald-700">{flash.success}</div>}<div className="mt-8 space-y-5">{requests.data.map((item) => <article key={item.id} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-black">{item.shop.name}</h2><p className="mt-1 text-sm text-slate-500">{item.submitter.name} · {item.submitter.email}</p></div><span className="h-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-bold capitalize text-amber-700">{item.status}</span></div><p className="mt-4 text-sm text-slate-600">{item.note || 'No seller note provided.'}</p><div className="mt-4 flex flex-wrap gap-2">{item.evidence.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer" className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-primary-700">Open evidence ↗</a>)}</div>{item.status === 'pending' && <ReviewForm requestItem={item} />}</article>)}{requests.data.length === 0 && <div className="rounded-3xl bg-white p-12 text-center text-slate-500">No verification requests.</div>}</div><div className="mt-8 flex flex-wrap gap-2">{requests.links.map((link) => link.url && <a key={link.label} href={link.url} className={`rounded-lg px-3 py-2 text-sm ${link.active ? 'bg-primary-700 text-white' : 'bg-white ring-1 ring-slate-200'}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div></section></AppLayout>;
}
