<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\Address;
use App\Models\DeliveryFee;
use App\Models\Product;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Inertia\Response;

class CartController extends Controller
{
    public function index(Request $request): Response { return Inertia::render('Cart/Index', $this->cartProps($request)); }
    public function add(Request $request, Product $product): RedirectResponse { abort_unless($product->status === 'active', 404); $qty = max(1, $request->integer('quantity', 1)); $cart = $request->session()->get('cart', []); $next = ($cart[$product->id] ?? 0) + $qty; abort_if($next > $product->stock, 422, 'Not enough stock available.'); $cart[$product->id] = $next; $request->session()->put('cart', $cart); return back()->with('success', 'Added to cart.'); }
    public function update(Request $request): RedirectResponse { $data = $request->validate(['items' => ['required', 'array'], 'items.*' => ['integer', 'min:1', 'max:1000']]); $ids = array_map('intval', array_keys($data['items'])); $products = Product::whereIn('id', $ids)->get()->keyBy('id'); $cart = []; foreach ($data['items'] as $id => $qty) { $id = (int) $id; abort_unless(isset($products[$id]) && $products[$id]->status === 'active' && $qty <= $products[$id]->stock, 422, 'Cart quantity is unavailable.'); $cart[$id] = (int) $qty; } $request->session()->put('cart', $cart); return back(); }
    public function remove(Request $request, int $product): RedirectResponse { $cart = $request->session()->get('cart', []); unset($cart[$product]); $request->session()->put('cart', $cart); return back(); }
    public function checkout(Request $request): Response { return Inertia::render('Cart/Checkout', [...$this->cartProps($request), 'addresses' => Address::where('user_id', $request->user()->id)->latest()->get()]); }
    public function placeOrder(Request $request): RedirectResponse { $data = $request->validate(['name' => ['nullable', 'string', 'max:120'], 'phone' => ['nullable', 'string', 'max:30'], 'address' => ['nullable', 'string', 'max:1000'], 'address_id' => ['nullable', 'integer', Rule::exists('addresses', 'id')->where('user_id', $request->user()->id)], 'payment_method' => ['required', 'in:cod']]); if ($data['address_id'] ?? null) { $saved = Address::where('user_id', $request->user()->id)->findOrFail($data['address_id']); $data = ['name' => $saved->recipient_name, 'phone' => $saved->phone, 'address' => trim($saved->address.', '.$saved->city.' '.$saved->region), 'payment_method' => $data['payment_method']]; } else { $data = validator($data, ['name' => ['required'], 'phone' => ['required'], 'address' => ['required'], 'payment_method' => ['required', 'in:cod']])->validate(); } $cart = $request->session()->get('cart', []); abort_if(empty($cart), 422, 'Your cart is empty.'); $order = DB::transaction(function () use ($cart, $data, $request): Order { $products = []; foreach ($cart as $id => $qty) { $product = Product::query()->lockForUpdate()->findOrFail($id); if ($product->status !== 'active' || $product->stock < $qty) throw ValidationException::withMessages(['cart' => ['A product is no longer available in the requested quantity.']]); $products[] = [$product, (int) $qty]; } $sellerIds = collect($products)->map(fn ($pair) => $pair[0]->seller_id)->unique(); if ($sellerIds->count() !== 1) throw ValidationException::withMessages(['cart' => ['Please checkout products from one seller at a time.']]); $subtotal = 0; foreach ($products as [$product, $qty]) { $subtotal += (float) $product->price * $qty; $product->decrement('stock', $qty); } $deliveryFee = DeliveryFee::getApplicableFee($subtotal); $order = Order::create(['order_number' => 'ORD-'.strtoupper(Str::random(10)), 'buyer_id' => $request->user()->id, 'seller_id' => $sellerIds->first(), 'shop_id' => $products[0][0]->shop_id, 'subtotal' => $subtotal, 'delivery_fee' => $deliveryFee, 'discount' => 0, 'total' => $subtotal + $deliveryFee, 'payment_method' => $data['payment_method'], 'status' => 'pending', 'delivery_address' => Arr::except($data, ['payment_method']), 'idempotency_key' => 'web-'.Str::uuid()]); foreach ($products as [$product, $qty]) $order->items()->create(['product_id' => $product->id, 'quantity' => $qty, 'unit_price' => $product->price, 'line_total' => (float) $product->price * $qty]); return $order; }); $request->session()->forget('cart'); return redirect('/orders/'.$order->id)->with('success', 'Order placed successfully.'); }
    public function orders(Request $request): Response { $status = $request->string('status')->toString(); $buyerOrders = Order::where('buyer_id', $request->user()->id); $query = Order::with(['shop', 'items.product'])->where('buyer_id', $request->user()->id); if ($status && in_array($status, ['pending', 'confirmed', 'preparing', 'shipped', 'delivered', 'completed', 'cancelled'], true)) $query->where('status', $status); $statusCounts = collect(['pending', 'confirmed', 'preparing', 'shipped', 'delivered', 'completed', 'cancelled'])->mapWithKeys(fn (string $value) => [$value => (clone $buyerOrders)->where('status', $value)->count()]); return Inertia::render('Orders/Index', ['orders' => $query->latest()->paginate(20)->withQueryString(), 'activeStatus' => $status ?: 'all', 'statusCounts' => $statusCounts]); }
    public function cancelOrder(Request $request, Order $order): RedirectResponse { abort_unless((int) $order->buyer_id === (int) $request->user()->id, 403); abort_unless($order->status === 'pending', 422, 'Only pending orders can be cancelled.'); DB::transaction(function () use ($order): void { foreach ($order->items()->lockForUpdate()->get() as $item) Product::whereKey($item->product_id)->lockForUpdate()->increment('stock', $item->quantity); $order->update(['status' => 'cancelled', 'cancelled_at' => now(), 'cancel_count' => (int) $order->cancel_count + 1]); }); return back()->with('success', 'Order cancelled successfully.'); }
    public function completeOrder(Request $request, Order $order): RedirectResponse { abort_unless((int) $order->buyer_id === (int) $request->user()->id, 403); abort_unless($order->status === 'delivered', 422, 'Only delivered orders can be completed.'); $order->update(['status' => 'completed', 'completed_at' => now()]); return back()->with('success', 'Order completed. You can now leave a review.'); }
    public function order(Request $request, Order $order): Response
    {
        $user = $request->user();
        abort_unless($user->isAdmin() || (int) $order->buyer_id === (int) $user->id || (int) $order->seller_id === (int) $user->id, 403);
        return Inertia::render('Orders/Show', ['order' => $order->load('items.product', 'shop', 'buyer:id,name,email', 'seller:id,name,email'), 'viewerRole' => $user->role]);
    }
    private function cartProps(Request $request): array { $cart = $request->session()->get('cart', []); $products = Product::with('shop:id,name')->whereIn('id', array_keys($cart))->where('status', 'active')->get()->keyBy('id'); $items = collect($cart)->map(fn ($qty, $id) => isset($products[$id]) ? ['product' => $products[$id], 'quantity' => $qty, 'line_total' => (float) $products[$id]->price * $qty] : null)->filter()->values(); $subtotal = (float) $items->sum('line_total'); return ['items' => $items, 'subtotal' => $subtotal, 'deliveryFee' => DeliveryFee::getApplicableFee($subtotal), 'sellerCount' => $items->pluck('product.seller_id')->unique()->count()]; }
}
