import { Link, usePage } from '@inertiajs/react';
import { AlertTriangle, BarChart3, Boxes, DollarSign, Package, Plus, Receipt, ShoppingBag, Users } from 'lucide-react';
import AppLayout from '../../Layouts/AppLayout';

type Props = { shop: { name: string; verification_status: string }; stats: { products: number; low_stock: number; orders: number; revenue: number }; recentOrders: { id: number; order_number: string; total: string | number; status: string; buyer?: { name: string } | null; created_at?: string }[] };
const money = (value: number) => `${value.toLocaleString()} MMK`;

export default function Dashboard() {
    const { shop, stats, recentOrders } = usePage<Props>().props;
    const cards = [{ label: 'Products', value: stats.products, icon: Package, href: '/seller/products', tone: 'bg-blue-50 text-blue-700' }, { label: 'Orders', value: stats.orders, icon: ShoppingBag, href: '/seller/orders', tone: 'bg-violet-50 text-violet-700' }, { label: 'Revenue', value: money(stats.revenue), icon: DollarSign, href: '/seller/reports', tone: 'bg-emerald-50 text-emerald-700' }, { label: 'Low stock', value: stats.low_stock, icon: Boxes, href: '/seller/inventory', tone: 'bg-amber-50 text-amber-700' }];
    const actions = [['/seller/products/create', 'Add product', Plus], ['/seller/pos', 'Open POS', DollarSign], ['/seller/inventory', 'Inventory', Boxes], ['/seller/expenses', 'Expenses', Receipt], ['/seller/reports', 'Reports', BarChart3], ['/seller/customers', 'Customers', Users]] as const;

    return <AppLayout><section className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-primary-700">Seller dashboard</p><h1 className="mt-2 text-3xl font-black text-gray-900 sm:text-4xl">Welcome back, {shop.name}</h1><p className="mt-2 text-gray-500">Manage products, sales, inventory, and shop performance.</p></div><span className="w-fit rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold capitalize text-emerald-700">{shop.verification_status}</span></div>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({ label, value, icon: Icon, href, tone }) => <Link key={label} href={href} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><p className="text-sm text-gray-500">{label}</p><span className={`rounded-xl p-2 ${tone}`}><Icon size={20} /></span></div><p className="mt-4 text-2xl font-black text-gray-900">{value}</p></Link>)}</div>
        {stats.low_stock > 0 && <Link href="/seller/inventory" className="mt-6 flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle size={20} /><span><strong>{stats.low_stock} product(s)</strong> are running low on stock. Review inventory now.</span></Link>}
        <div className="mt-8"><h2 className="text-lg font-bold text-gray-900">Quick actions</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{actions.map(([href, label, Icon]) => <Link key={href} href={href} className="flex flex-col items-center gap-2 rounded-2xl bg-white p-4 text-center text-sm font-semibold text-gray-700 shadow-sm ring-1 ring-gray-100 hover:bg-primary-50 hover:text-primary-700"><Icon size={22} /><span>{label}</span></Link>)}</div></div>
        <div className="mt-8 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-gray-900">Recent orders</h2><Link href="/seller/orders" className="text-sm font-bold text-primary-700">View all</Link></div>{recentOrders.length === 0 ? <p className="py-10 text-center text-gray-500">No orders yet.</p> : <div className="mt-4 divide-y divide-gray-100">{recentOrders.map((order) => <Link key={order.id} href={`/orders/${order.id}`} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="font-bold text-gray-900">#{order.order_number}</p><p className="truncate text-sm text-gray-500">{order.buyer?.name || 'Buyer'} · <span className="capitalize">{order.status}</span></p></div><p className="shrink-0 font-bold text-primary-700">{money(Number(order.total))}</p></Link>)}</div>}</div>
    </section></AppLayout>;
}
