import { Link, useForm, usePage } from '@inertiajs/react';
import type { FormEvent } from 'react';
import AppLayout from '../../Layouts/AppLayout';

type Shop = { name: string; verification_status: string; verified: boolean; rejection_note?: string | null };
type Verification = { id: number; status: string; evidence: string[]; note?: string | null; reviewed_at?: string | null; created_at: string };
type Props = { shop: Shop; requests: Verification[]; flash?: { success?: string } };

export default function Verification() {
    const { shop, requests, flash } = usePage<Props>().props;
    const form = useForm({ evidence: '', note: '' });
    const pending = requests.some((item) => item.status === 'pending');
    const submit = (e: FormEvent) => { e.preventDefault(); form.transform((data) => ({ ...data, evidence: data.evidence.split(/\s*,\s*|\n/).filter(Boolean) })).post('/seller/verification'); };
    return <AppLayout><section className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Seller verification</p><h1 className="mt-2 text-4xl font-black">{shop.name}</h1></div><span className={`rounded-full px-4 py-2 text-sm font-bold capitalize ${shop.verified ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{shop.verification_status}</span></div>{flash?.success && <div className="mt-6 rounded-xl bg-emerald-50 p-4 text-emerald-700">{flash.success}</div>}{shop.rejection_note && <div className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">Previous review: {shop.rejection_note}</div>}<div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-black">Submit documents</h2><p className="mt-2 text-sm text-slate-500">Paste one or more public evidence image/document URLs, separated by commas or new lines.</p><label className="mt-6 block text-sm font-bold">Evidence URLs<textarea disabled={pending || shop.verified} value={form.data.evidence} onChange={(e) => form.setData('evidence', e.target.value)} className="mt-2 min-h-36 w-full rounded-xl border-slate-300" /></label><label className="mt-5 block text-sm font-bold">Note<textarea disabled={pending || shop.verified} value={form.data.note} onChange={(e) => form.setData('note', e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border-slate-300" /></label>{Object.values(form.errors).map((error) => <p key={error} className="mt-3 text-sm text-red-600">{error}</p>)}<button disabled={pending || shop.verified || form.processing} className="mt-6 w-full rounded-xl bg-teal-700 px-4 py-3 font-bold text-white disabled:bg-slate-300">{shop.verified ? 'Shop verified' : pending ? 'Review pending' : 'Submit for review'}</button></form><div><h2 className="text-xl font-black">Request history</h2><div className="mt-4 space-y-3">{requests.map((item) => <div key={item.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between"><span className="font-bold capitalize">{item.status}</span><span className="text-xs text-slate-400">{new Date(item.created_at).toLocaleDateString()}</span></div><p className="mt-2 text-sm text-slate-500">{item.note || 'No note provided.'}</p></div>)}{requests.length === 0 && <p className="text-slate-500">No requests submitted yet.</p>}</div><Link href="/dashboard" className="mt-6 inline-block font-bold text-teal-700">← Back to dashboard</Link></div></div></section></AppLayout>;
}
