// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-s5R4gzElq4D5NatWkcklF198fTEvRo',
    appId: '1:304535507982:web:b960bdb0f2bc1652fb985f',
    messagingSenderId: '304535507982',
    projectId: 'padaytharpin-app',
    authDomain: 'padaytharpin-app.firebaseapp.com',
    storageBucket: 'padaytharpin-app.firebasestorage.app',
    measurementId: 'G-F7JE4SNWDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8xRXeNX3E6nOyjsyt-3SoV48K0T2t3DY',
    appId: '1:304535507982:android:26acbb11be9690f6fb985f',
    messagingSenderId: '304535507982',
    projectId: 'padaytharpin-app',
    storageBucket: 'padaytharpin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD48Tdi1sMmRH_4miqMpQuPCUgMus3NVM0',
    appId: '1:304535507982:ios:f59229ce9856060ffb985f',
    messagingSenderId: '304535507982',
    projectId: 'padaytharpin-app',
    storageBucket: 'padaytharpin-app.firebasestorage.app',
    iosBundleId: 'com.marketplace.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD48Tdi1sMmRH_4miqMpQuPCUgMus3NVM0',
    appId: '1:304535507982:ios:f59229ce9856060ffb985f',
    messagingSenderId: '304535507982',
    projectId: 'padaytharpin-app',
    storageBucket: 'padaytharpin-app.firebasestorage.app',
    iosBundleId: 'com.marketplace.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1-s5R4gzElq4D5NatWkcklF198fTEvRo',
    appId: '1:304535507982:web:332f55756cf92b78fb985f',
    messagingSenderId: '304535507982',
    projectId: 'padaytharpin-app',
    authDomain: 'padaytharpin-app.firebaseapp.com',
    storageBucket: 'padaytharpin-app.firebasestorage.app',
    measurementId: 'G-7D755WZRVV',
  );
}
